linreg <- setRefClass("linreg",
                      fields = list(formula="formula",
                                    data="data.frame",
                                    X="matrix",
                                    Y="matrix",
                                    Xt="matrix",
                                    XtX="matrix",
                                    B="matrix",
                                    Yfit="matrix",
                                    E="matrix",
                                    dof="integer",
                                    sigsq="numeric",
                                    Estd="numeric",
                                    N="numeric",
                                    P="numeric",
                                    var_B="matrix",
                                    tval="matrix",
                                    pval="matrix",
                                    Formula="formula",
                                    Data="character",
                                    sqrtstresiduals="matrix")
)